### ISSUE TITLE
binlog pos not catch up with master after upstream master-slave switch

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1930] opened 2021-07-29 03:00 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
upstream master-slave switch
2. What did you expect to see?
syncer catch up with master: true
3. What did you see instead?
syncer catch up with master: false
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```

**Comment by lance6716** [comment] 2021-12-06 03:26
can't reproduce, close it

**Closed by lance6716** 2021-12-06 03:26 UTC
Labels: type/bug, severity/major, affected-v2.0.2, affected-v2.0.3, affected-v2.0.4, affected-v2.0.5, affected-v2.0.6, affected-v2.0.7
