### ISSUE TITLE
Unable to reach batch with a large worker count

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#2087] opened 2021-09-02 16:58 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
start a start with 1024 worker and 1024 batch
2. What did you expect to see?
statementsize is 1024 or at least not too small.
3. What did you see instead?
![image](https://user-images.githubusercontent.com/35025882/131884675-f89b85af-b27b-4ad6-b309-af821f2d43ca.png)
4. Root Cause
We [wait](https://github.com/pingcap/dm/blob/3cb459a17c24d1cb8d506c9a7b5094a5dacab717/syncer/syncer.go#L79) 10ms for a sql worker, if no new binlog for that worker in 10ms, flush the sql. If we config a large worker count, e.g. 1024, that means we should pull 1024*(1000s/10ms)=102k/s binlog to reach the batch...
In a normal case, if we pull less than 20k binlog per second from upstream, that means if worker count bigger than 200 = 20k/(1s/10ms)), the sql statement size usually is a small size.

**Comment by lance6716** [comment] 2021-12-06 03:37
I think this is by design 🤔 if downstream execute SQL slowly we can accumulate enough batch 

will close this issue and fell free to open it **in ticdc**

**Closed by lance6716** 2021-12-06 03:37 UTC
Labels: type/bug, severity/minor, affected-v2.0.2, affected-v2.0.3, affected-v2.0.4, affected-v2.0.5, affected-v2.0.6
